version: "3"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    ports:
      - 8123:8123
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true

  ssh-tunnel:
    container_name: ssh-tunnel
    build: ./ssh-tunnel
    volumes:
      - ~/.ssh:/root/.ssh
    depends_on:
      - homeassistant
    restart: unless-stopped
